# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndhPiBvTf3cKQq0JAm1Az4yiQwMhkB50
"""

from diffusers import DDPMScheduler
from diffusers.models import UNet2DModel
import torch

def create_model(learning_rate):
    # Define Model, Loss Function, Optimizer, and Scheduler
    model = UNet2DModel()
    loss_fn = torch.nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = DDPMScheduler()
    return model, loss_fn, optimizer, scheduler